export { HelpComponent } from './help/help.component';
export { HomeComponent } from './home/home.component';
export { InstructorProfileComponent } from './instructor-profile/instructor-profile.component';
export { InstructorProfilePublicComponent } from './instructor-profile-public/instructor-profile-public.component';
export { SettingsComponent } from './settings/settings.component';
export { CourseDetailComponent } from './course-detail/course-detail.component';
export { ExplorarComponent } from './explorar/explorar.component';
export { FeedbackComponent } from './feedback/feedback.component';
export { DesarrollarCursoComponent } from './desarrollar-curso/desarrollar-curso.component';